### ISSUE TITLE
bootloader error

### ISSUE THREAD

**Issue by LedArts** [asalminen/arduinobootloader#1]
sir i am trying to upload bootloader .hex file by my universal programmer to a blank atmega328 ic
but its not working.
what should i do plz tell me.
and also i am trying to compile the c file but it gives the error
'NUM_LED_FLASHES' was not declared in this scope

plz help me

**Comment by asalminen** [comment]
I use "make atmega328" to compile. 
From makefile  "atmega328: CFLAGS += '-DMAX_TIME_COUNT=F_CPU>>1' '-DNUM_LED_FLASHES=1' -DBAUD_RATE=57600"

I use avrdude to flash. Fuses and my flash params are in file "flash".
"
avrdude -patmega328p -cstk500v2 -Pusb -e -Ulock:w:0x3F:m -Uefuse:w:0x05:m -Uhfuse:w:0xDA:m -Ulfuse:w:0xFF:m
avrdude -patmega328p -cstk500v2 -Pusb -Uflash:w:ATmegaBOOT_168_atmega328.hex:i -Ulock:w:0x0F:m
"
After bootloader flash, bootloader is waiting 10 sec and then starting bootloader again... Thus you need to flash some sketch to it to do something. First sketch flash can be done whit pure rx/tx whitout any reset as bootloader is on all time "avrdude -p atmega328p -c arduino -P /dev/rfcomm0 -b 57600 -D -U flash:w:main.hex:i" . Later sketch flashes needs sketch that has some way to watchdog reset chip before flash.

Br, 
Aki
